### PR TITLE
change affirmation for avis

### PR DESCRIPTION
**Pull request by virgile-dev**

### CODE REVIEW

**Comment by virgile-dev** [comment]
Sorry for the first pull request, I didn't see it had conflicts. Should be ok now.

**Comment by virgile-dev** [comment]
Hey @mbjorkegren ! 
Is there anything stopping you for merging this ?
Let me know :)

**Comment by mbjorkegren** [comment]
Hey @virgile-dev, yes, I'll ping you on Slack

**Comment by patcon** [comment]
@virgile-dev hiya! Reviewing old PRs, and noticed your translation suggestion didn't get in. Do you still feel it's an improvement? If so, is love to go to bat for getting it merged :)

**Pull request closed without merging**
